stages:
  preprocess:
    cmd: python CICD_LAB/src/preprocess.py
    deps:
      - CICD_LAB/data/winequality-red.csv
      - CICD_LAB/src/preprocess.py
    outs:
      - CICD_LAB/data/processed.csv

  train:
    cmd: python CICD_LAB/src/train.py
    deps:
      - CICD_LAB/data/processed.csv
      - CICD_LAB/src/train.py
    params:
      - learning_rate
      - epochs
    outs:
      - CICD_LAB/models/model.pkl
    metrics:
      - CICD_LAB/metrics.json
